diff_drive_node:
  ros__parameters:
    robot_type: "differencial drive"  # string
    wheel_radious: 0.03  # double
    wheel_distance: 0.1 # double

dammy_enc_node:
  ros__parameters:
    robot_type: "differencial drive"
    lxenc_radious: 0.01
    azenc_radious: 0.01

states_pub_node:
  ros__parameters:
    robot_type: "differencial drive"
    wheel_radious: 0.03
    wheel_distance: 0.1
    lxenc_radious: 0.01
    azenc_radious: 0.01



joy_transrate_node:
  ros__parameters:
    robot_type: "differencial drive"  # string
    max_lx: 0.25  # double
    max_az: 6.0 # double


