# omni_states_nodeのパラメータ
omni_states_node:
  ros__parameters:
    robot_type: "omni" #ロボットの種類
    wheel_radious: 0.065 #駆動輪半径m
    wheel_distance: 0.25 #駆動輪中心間距離m
    enc_radious: 0.03 #エンコーダ半径m
    enc_distance: 0.15 #回転エンコーダーーロボット中心間距離

# omni_joy_nodeのパラメータ
omni_joy_node:
  ros__parameters:
    robot_type: "omni" #ロボットの種類
    max_lx: 0.5 #x方向最大速度m/s
    max_ly: 0.5 #y方向最大速度m/s
    max_az: 1.57 #z周り最大角速度rad/s

# omni_hardware_nodeのパラメータ
omni_hardware_node:
  ros__parameters:
    robot_type: "omni" #ロボットの種類
    wheel_radious: 0.065 #駆動輪半径m
    wheel_distance: 0.25 #駆動輪中心間距離m
    enc_radious: 0.03 #エンコーダ半径m
    enc_distance: 0.15 #回転エンコーダーーロボット中心間距離




